---
- name: Deploy Docker Container
  hosts: all
  vars:
    deploy_dir: ""
    ports: ""
    environment_vars: ""
    devices: ""
    restart_policy: "unless-stopped"

  tasks:
    - name: set deploy directory
      set_fact:
        final_dir: "{{ deploy_dir if deploy_dir != '' else ansible_env.HOME + '/' + (image_name | split('/') | last | split(':') | first) }}"

    - name: create deploy directory
      file:
        path: "{{ final_dir }}"
        state: directory

    - name: template docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ final_dir }}/docker-compose.yml"

    - name: start container
      command: docker compose up -d
      args:
        chdir: "{{ final_dir }}"
